apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: dhcims-msapoc-dev
data:
  application.properties: |-
    server.port=${port:8080}
    spring.application.name=bff
    security.publicKey=http://user:8080/publicKey
    #remoteservice
    service.saveClinicalNote=http://clinicalnote:8080/saveClinicalNote
    service.updateClinicalNote=http://clinicalnote:8080/updateClinicalNote
    service.saveAttendingDiagnosis=http://diagnosis:8080/saveAttendingDiagnosis
    service.updateAttendingDiagnosis=http://diagnosis:8080/updateAttendingDiagnosis
    service.saveChronicDiagnosis=http://diagnosis:8080/saveChronicProblem
    service.updateChronicDiagnosis=http://diagnosis:8080/updateChronicProblem
    service.savePrescription=http://order:8080/savePrescription
    service.updatePrescription=http://order:8080/updatePrescription
    #saga
    #alpha.cluster.address=saga-server:8080
    cims.redis.url=redis
    cims.redis.port=6379
    alpha.cluster.address=saga-server:8080
    logging.path=/app-logs
    logging.config=classpath:logback.xml