apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: dhcims-msapoc-dev
data:
  application.properties: |-
    server.port=${port:8080}
    spring.application.name=bff
    security.publicKey=http://user/publicKey
    #remoteservice
    service.saveClinicalNote=http://clinicalnote/saveClinicalNote
    service.updateClinicalNote=http://clinicalnote/updateClinicalNote
    service.saveAttendingDiagnosis=http://diagnosis/saveAttendingDiagnosis
    service.updateAttendingDiagnosis=http://diagnosis/updateAttendingDiagnosis
    service.saveChronicDiagnosis=http://diagnosis/saveChronicProblem
    service.updateChronicDiagnosis=http://diagnosis/updateChronicProblem
    service.savePrescription=http://order/savePrescription
    service.updatePrescription=http://order/updatePrescription
    #saga
    #alpha.cluster.address=saga-server:8080
    cims.redis.url=redis
    cims.redis.port=6379
    alpha.cluster.address=alpha.test-middleware:8080
    logging.path=/app-logs
    logging.config=classpath:logback.xml